class PorthException(Exception): ...

class StackException(PorthException): ...
class ParserException(PorthException): ...

class NotEnoughArguments(StackException): ...
class NotEnoughStuffOnTheStack(StackException): ...
class BadTypesOnTheStack(StackException): ...
class UnknownTypeOnTheStack(StackException): ...

class TooManyNestedIncludes(ParserException): ...
class TooManyNestedMacros(ParserException): ...